name: Deployment removal from Railway

on:
  workflow_dispatch:

jobs:
  remove_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Railway
        run: npm i -g @railway/cli@3.0

      - name: Remove deployment
        run: railway down -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
