name: Deployment removal from Railway

on:
  workflow_dispatch:

jobs:
  remove_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Ubuntu with cURL and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Fetch deployments with SUCCESS status
        id: fetch_deployments
        run: |
          query='query{
            project(id: "$RAILWAY_PROJECT_ID"){
              id
              name
              deployments(){
                edges{
                  node{
                    id
                    status
                  }
                }
              }
            }
          }'
          response=$(curl -X POST \
            --url https://backboard.railway.app/graphql/v2 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_PERSONAL_TOKEN }}" \
            -d "{\"query\": \"$query\"}")

          echo "::set-output name=response::$response"
